# Generated by Django 5.1.6 on 2025-03-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("x", "0002_meep"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Meep",
            new_name="Tweet",
        ),
    ]
