# Generated by Django 5.1.6 on 2025-03-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("x", "0003_rename_meep_tweet"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
