# Generated by Django 5.1.6 on 2025-03-10 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("x", "0004_customuser_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="tweet_like", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
