# Generated by Django 5.1.6 on 2025-03-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("x", "0005_tweet_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="facebook_link",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="homepage_link",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="instagram_link",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="linkedin_link",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_bio",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
